import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import grovesRouter from "./groves";
import treesRouter from "./trees";
import satelliteRouter from "./satellite";
import heritageRouter from "./heritage";
import tasksRouter from "./tasks";
import fieldVisitsRouter from "./field-visits";
import harvestRouter from "./harvest";
import pressingRouter from "./pressing";
import mediaRouter from "./media";
import dashboardRouter from "./dashboard";
import aiRouter from "./ai";
import storageRouter from "./storage";
import photoLibraryRouter from "./photo-library";
import photoAnalysisRouter from "./photo-analysis";
import sessionRouter from "./session";
import activitiesRouter from "./activities";
import phenologyRouter from "./phenology";
import managerFlagsRouter from "./manager-flags";
import pestDiseaseRouter from "./pest-disease";
import trapsRouter from "./traps";
import treatmentsRouter from "./treatments";
import irrigationRouter from "./irrigation";
import weatherRouter from "./weather";
import soilTestsRouter from "./soil-tests";
import treeGeometryRouter from "./tree-geometry";
import bottlingRouter from "./bottling";
import reportsRouter from "./reports";
import sensorsRouter from "./sensors";
import publicRouter from "./public";
import forecastRouter from "./forecast";

const router: IRouter = Router();

router.use(healthRouter);
router.use(dashboardRouter);
router.use(usersRouter);
router.use(grovesRouter);
router.use(treesRouter);
router.use(satelliteRouter);
router.use(heritageRouter);
router.use(tasksRouter);
router.use(fieldVisitsRouter);
router.use(harvestRouter);
router.use(pressingRouter);
router.use(mediaRouter);
router.use(aiRouter);
router.use(storageRouter);
router.use(photoLibraryRouter);
router.use(photoAnalysisRouter);
router.use(sessionRouter);
router.use(activitiesRouter);
router.use(phenologyRouter);
router.use(managerFlagsRouter);
router.use(pestDiseaseRouter);
router.use(trapsRouter);
router.use(treatmentsRouter);
router.use(irrigationRouter);
router.use(weatherRouter);
router.use(soilTestsRouter);
router.use(treeGeometryRouter);
router.use(bottlingRouter);
router.use(reportsRouter);
router.use(sensorsRouter);
router.use(forecastRouter);
router.use(publicRouter);

export default router;
